name: black

on:
  push:
    paths:
      - '**.py'

defaults:
  run:
    shell: bash

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black isort
    - name: Version
      run: |
        python --version
        black --version
        isort --version
    - name: Run isort
      run: |
        isort src
    - name: Run black
      run: |
        black src tests
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "[skip ci] Apply black changes"
