name: tests

on: [push, pull_request]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: "recursive"

    - name: Setup uv
      id: setup-uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true

    - name: Print the installed version
      run: echo "Installed uv version is ${{ steps.setup-uv.outputs.uv-version }}"

    - name: Set up Python ${{ matrix.python-version }} and install dependencies
      run: |
        uv python install ${{ matrix.python-version }}
        uv sync --python ${{ matrix.python-version }} --extra test --extra build --frozen

    - name: Test with pytest
      run: uv run pytest
